image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
    - build

before_script:
    - "dotnet restore GameSociation.Backend.sln"

build:
    stage: build
    script:
        - "dotnet build GameSociation.Backend.sln"
